### ISSUE TITLE
How can i hide the number input’s spin box ?

### ISSUE THREAD

**Issue by s1k3** [fengyuanchen/vue-number-input#12]
Hi i want to hide the spinners from the number component. I have tried some css code but does not seem to work. Below is the code for hiding the css

`<style scoped>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
        -webkit-appearance: none;
    }

    input[type=number] {
        -moz-appearance:textfield;
    }
</style>`

**Comment by fengyuanchen** [comment]
Not to scoped the style:

```css
<style>
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
}
</style>
```
